[build]
  publish = "dist"
  command = "echo '@seenelm:registry=https://npm.pkg.github.com' > .npmrc && echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' >> .npmrc && npm install && vite build"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
