[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# This command runs before the build to set up authentication and install dependencies
[build.lifecycle]
  onPreBuild = """
    echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc
    echo "@seenelm:registry=https://npm.pkg.github.com/" >> .npmrc
    npm ci
  """

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
