[build]
  publish = "dist"
  command = "echo '@seenelm:registry=https://npm.pkg.github.com' > .npmrc && echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> .npmrc && npm install && vite build"

[build.environment]
  NPM_TOKEN = "${VITE_GITHUB_TOKEN}"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
