name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build unit test Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          push: false
          load: true
          tags: train-web-app:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_AUTH_TOKEN=${{ secrets.PACKAGE_TOKEN }}
        env:
          DOCKER_BUILDKIT: 1

      - name: Run unit tests
        run: docker run --rm -e VITE_FIREBASE_API_KEY="${{ secrets.FIREBASE_API_KEY }}" -e VITE_FIREBASE_AUTH_DOMAIN="${{ secrets.FIREBASE_AUTH_DOMAIN }}" -e VITE_FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}" -e VITE_FIREBASE_STORAGE_BUCKET="${{ secrets.FIREBASE_STORAGE_BUCKET }}" -e VITE_FIREBASE_MESSAGING_SENDER_ID="${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" -e VITE_FIREBASE_APP_ID="${{ secrets.FIREBASE_APP_ID }}" train-web-app:test

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build E2E test Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: e2e
          push: false
          load: true
          tags: train-web-app:e2e
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_AUTH_TOKEN=${{ secrets.PACKAGE_TOKEN }}
        env:
          DOCKER_BUILDKIT: 1

      - name: Run E2E tests
        run: docker run --rm train-web-app:e2e
